version: "3.9"
services:
  app:
    container_name: mkv_app
    build: .
    # volumes:
      # - .:/opt/app/api
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_HOST: mkv-mysql
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mkv-mysql
    networks:
      - fullstack

  mkv-mysql:
    image: mysql:8.0
    container_name: mkv-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_ROOT_HOST: ${MYSQL_HOST} 
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mkv-mysql
    environment:
      PMA_HOST: mkv-mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PORT: ${MYSQL_PORT}
      PMA_PASSWORD: ${MYSQL_PASS}
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


networks:
  fullstack:
    driver: bridge