version: "3.9"
services:

  backend:
    container_name: mkv_stage_backend
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_HOST: mkv-mysql
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: mkv-redis      
      REDIS_PORT: ${REDIS_PORT} 
      ACCESS_SECRET: ${ACCESS_SECRET}     
      REFRESH_SECRET: ${REFRESH_SECRET}    
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mkv-mysql
      - mkv-redis
    networks:
      - fullstack
    volumes:
      - main_app:/usr/src/app
  
  auth:
    container_name: auth-backend
    build: 
      dockerfile: Dockerfile
      context: ./auth
    environment:
      REDIS_HOST: mkv-redis      
      REDIS_PORT: ${REDIS_PORT} 
    ports:
      - 9080:9080
    restart:
      on-failure
    depends_on:
      - mkv-redis
    networks:
      - fullstack
    volumes:
      - auth_app:/usr/src/app


  mkv-mysql:
    image: mysql:8.0
    container_name: mkv-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_ROOT_HOST: ${MYSQL_HOST} 
    networks:
      - fullstack
    volumes:
      - database_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mkv-mysql
    environment:
      PMA_HOST: mkv-mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PORT: ${MYSQL_PORT}
      PMA_PASSWORD: ${MYSQL_PASS}
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack

  mkv-redis:
    container_name: mkv-redis
    hostname: mkv-redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - database_redis:/data
    networks:
      - fullstack
  
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    depends_on:
      - mkv-redis
    environment:
      - REDIS_HOSTS=local:mkv-redis:6379
    ports:
      - 8081:8081
    networks:
      - fullstack

volumes:
  main_app:
  auth_app:
  database_mysql:  
  database_redis:     

networks:
  fullstack:
    driver: bridge