version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - "3406:3406"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_NAME}
    networks:
      - fullstack

  adminer:
    image: adminer
    restart: always
    ports:
      - "4080:4000"
    networks:
      - fullstack

  app:
    name: mkv_app
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "8080:8080"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge