name: Build and Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:


  build:
    runs-on: ubuntu-latest
  
    env: 
      DB_NAME: test
      DB_USER: root
      DB_PASS: root
      DB_HOST: localhost
  
    steps:
    - uses: actions/checkout@v3

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASS }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Go Server
      run: go build -v ./cmd/main/main.go

    - name: Configure Test environment variables
      run: |
        cp .env_sample .env
        sed -i "s/example-dns/${{ env.DB_USER }}:${{ env.DB_PASS }}@tcp(${{ env.DB_HOST }}/${{ job.services.mysql.ports['3306'] }})/(${{ env.DB_NAME }})" .env

    - name: Run Testsuite
      run: go test -v ./...
