name: Build and Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:


  build:
    runs-on: ubuntu-latest
  
    env: 
      DB_NAME: test
      DB_USER: root
      DB_PASS: root
      DB_HOST: localhost
      DB_PORT: 3036

  
    steps:
    - uses: actions/checkout@v3

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASS }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Go Server
      run: go build -v ./main.go
      env:
        API_BASE: / api/stage

    - name: Configure Test environment variables
      run: |
        cp .env_sample .env
        echo $DSN
        sed -i "s/dns/$DSN/" .env
      env:
        DSN: ${{ env.DB_USER }}:${{ env.DB_PASS }}@tcp(${{ env.DB_HOST }}\/${{ env.DB_PORT }})\/${{ env.DB_NAME }}  

    - name: Run Testsuite
      run: go test -v ./...
